### PR TITLE
Download and install, locally, meson

### PR DESCRIPTION
**Pull request by guruDanny67**
Resolv #108. 

Now it's time to use all these tools we download 👍

### CODE REVIEW

**Comment by nacho** [comment]
Thanks! BTW I think the next step would be to factor out a class to make the unzip stuff so you can share it between the tools

**Comment by TingPing** [comment]
btw Python has built in `zipfile` module without the need of another dep, dunno if that is robust enough for your needs.

**Comment by nacho** [comment]
@TingPing I'd definitely prefer that indeed so we avoid another dep in msys2. @guruDanny67 mind having a look at it?

**Comment by guruDanny67** [comment]
I don't think about it but it's something to look to avoid another, even if small, dependendency.

I'll take a look to see if it's ok or it's too much work or if it presents some glich (I don't think, we know wich zip file we need to extract so this should work).

**Pull request merged**
