### PR TITLE
fix PythonPath when build some libraries

### PR DESCRIPTION
**Pull request by wsw0108**
if python is not installed in default dir(C:\Python27), for example using [Miniconda](http://conda.pydata.org/miniconda.html)

### CODE REVIEW

**Comment by nacho** [comment]
Here I think we could go at a lower level and set it where we set the configuration?

**Comment by wsw0108** [comment]
did you mean that do the replacing  in *.vcxproj?

**Comment by nacho** [comment]
Oops, missed this comment, no, I mean if it would make sense to just set it somewhere here like it is done for the configuration:
https://github.com/wingtk/gtk-win32/blob/master/build.py#L126

**Comment by nacho** [comment]
Or probably even better here:
https://github.com/wingtk/gtk-win32/blob/master/build.py#L1145

**Comment by wsw0108** [comment]
@nacho It more reasonable

**Comment by nacho** [comment]
Patch looks good to me. Does it work well for you?

**Comment by wsw0108** [comment]
Yes. I rebuild glib, gtk3 with this changes, and it works as expected.

**Comment by nacho** [comment]
Did you try to build some of the other projects, specially the ones that do not provide a PythonPath variable?

**Comment by wsw0108** [comment]
I had choose 'fontconfig' and 'libpng' for examples. 
Run 
```powershell
python build.py -d build -p x64 fontconfig libpng --python-dir=C:\Miniconda2
```
It OK.

**Comment by wsw0108** [comment]
I also think that the default value for `--python-dir` can be change to the directory from where `python` was launched, 
```python
import sys
opts.python_dir = sys.prefix
```

**Comment by nacho** [comment]
sounds like a good idea, can you provide another pull request for that?

**Pull request merged**
