### PR TITLE
pango: apply patch for read 'pango.aliases' file

### PR DESCRIPTION
**Pull request by hsccr**
Since version 1.37.0, the code has been deleted read pango.aliases.
So I have added the code to patch.
pango library has been modified to the latest version ( 1.40.1 ).

### CODE REVIEW

**Comment by nacho** [comment]
Adding @fanc here, since he did not like this approach and had something else in mind.

**Comment by hsccr** [comment]
He and I are working together.
So, no problem will be .

**Comment by hsccr** [comment]
I 'm sorry to the wrong understanding .
I will ask the `PR` to 'fanc999'

**Comment by hsccr** [comment]
I could not have understanding.
How can I do `Adding @fanc999`??
Please explain more details.
I'm sorry to bother you

**Pull request closed without merging**
