### PR TITLE
Update Perl path

### PR DESCRIPTION
**Pull request by Sineaggi**
Reuse perl installed in $PerlDirectory.

### CODE REVIEW

**Comment by nacho** [comment]
Actually I think we should have the other way around. I've seen some perl scripts pointing to c:\perl. So I think we should update the readme and the other parts of the code to install perl in c: and point to it.

**Comment by Sineaggi** [comment]
Sounds reasonable.
Perhaps we could update `$PerlDirectory` to point to `c:\perl`, and do away with the  `$platform` nonsense.

**Comment by Sineaggi** [comment]
Updated with proposed changes.

**Comment by nacho** [comment]
I think we can close this one now?

**Comment by Sineaggi** [comment]
I was just thinking that hard-coding the Perl path in various places isn't a terribly good design. That way if some people really want to use a different Perl location they can.

**Comment by INTITY** [comment]
If my x64 platform, but I need to compile Win32 stack, I can use Perl x64?

**Comment by pbor** [comment]
yes, just install it in C:\Perl

**Comment by nacho** [comment]
Closing this since it is now obsolete

**Pull request closed without merging**
