### PR TITLE
Add sha256 hash check of downloaded files, with option to perform onl…

### PR DESCRIPTION
**Pull request by guruDanny67**
…y the check without build

### CODE REVIEW

**Comment by guruDanny67** [comment]
I messed up my branch and I can fix the things (I'm still learning to use git) so I make a clean pull request. with all your request of modification, with only one commit.

Many thanks.

**Comment by nacho** [comment]
Awesome thanks a lot

**Comment by guruDanny67** [comment]
Many thanks to you. 

I'm (slowing) take a look to add the gobject-introspection and, after that, pygobject for python 3.5 to the build system to have a complete gtk3/visual studio/python solution.

I already add pkg-config to the projects (it's needed because, unlike the msys2 one, you need the --msvc-syntax option to build the introspection modules): would you like a pull request to add it to the current build?

**Comment by nacho** [comment]
Sure I wanted to add it for a while already. Grazie

**Comment by nacho** [comment]
Forgot to say that the hexchat gtk-win32 already supports gobject-introspection so you could have a look if you can copy something from them. @tingping might as well help here since he did that work

**Comment by guruDanny67** [comment]
Yes, I see it and use what they've done but actually the build is a manual operation and I need to clean it up a little.

**Pull request merged**
