### PR TITLE
Use the internal zip handling instead of the msys2 one

### PR DESCRIPTION
**Pull request by guruDanny67**
I like python :)

### CODE REVIEW

**Comment by nacho** [comment]
Great stuff thanks a lot

**Comment by guruDanny67** [comment]
You're welcome. If I have a bit of time I try tomorrow to integrate graphene to see if meson & ninja works or there is something more to do.

**Comment by TingPing** [comment]
As I mentioned in the other issue, you need pkg-config and the pkg-config files for every project.

**Comment by guruDanny67** [comment]
For graphene or for meson/ninjia ?

Actually is possibile to build pkg-config with the stack and I need to see if ir will be a dependecies of graphene (with meson/ninja for the build  and glib for the gojbect stuff).

**Comment by TingPing** [comment]
> For graphene or for meson/ninjia ?

Meson uses `pkg-config` for dependencies.

> Actually is possibile to build pkg-config with the stack

Yea its trivial to build, we do it in hexchat/gtk-win32.

The annoying part is you have to generate/install the pc files from every project.

**Comment by nacho** [comment]
I just mailed with Fan, most of the projects should already provide a python script to generate the pc file: See i.e https://git.gnome.org/browse/atk/tree/win32/atkpc.py

**Comment by guruDanny67** [comment]
Yes. There are pc_base.py and replace.py as the base modules with one main module (atkpc.py for atk,  glibpc.py for glib, ... ) that take care of creating the .pc file. If you check at the end of the build of the gtk3 stack you end up with the (correct) .pc file on lib/pkgconfig (and graphene founds the gobject dipendency).
For graphene the build and installation of the .pc file is handled directly by the meson script that get the data from the build (the prefix dir, for examples), as the gobject introspection gir/typelib generation.
Even if it's a simple library that's is easily buildable manually having it working completely (pkgconfig generation, dependencies scan, gobject introspection generation, gtk-doc generation, ...) in the build.py script can be useful as a test ground for other stuff/libraries.

**Comment by guruDanny67** [comment]
Just for reference, the lib/pkgconfig directory is created by the glib build that adds some .pc files:
        gio-2.0.pc
        gio-windows-2.0.pc
        glib-2.0.pc
        gmodule-2.0.pc
        gmodule-export-2.0.pc
        gmodule-no-export-2.0.pc
        gobject-2.0.pc
        gthread-2.0.pc

We have pango that puts some other files:
        pango.pc
        pangocairo.pc
        pangoft2.pc
        pangowin32.pc

the libraries build for gtk3 puts more:   
    atk -> atk.pc
    gtk-pixbuf -> gdl-pixbud-2.0.pc

and finally for gtk3 we have:
        gail-3.0.pc
        gdk-3.0.pc
        gdk-win32-3.0.pc
        gtk+-3.0.pc

so the actual pkg-config support is good.

BTW Fan is making an awesome work on supporting gtk build on windows, the first that's coming to my mind is that on all the Gtk library there is the xxx-msvc-introspection-msvc.mak to build the typelib. Many many thanks to him!

**Comment by nacho** [comment]
Adding @fanc999 for the thanks

@guruDanny67 So I guess we just need to install the pkg-config files on the right directory?
Also I asked fan if he could add the pkg-config support to libsoup

**Comment by guruDanny67** [comment]
I'm looking at it right now. 

The pkg-config.exe is installed in the gtk bin directory, where it should be (in this way the correct lib/pkgconfig dir is look for the parameter and the builded libs/include/... are used). Especially if you have some mingw directory on the path calling pkg-config can result in the wrong directory get looked (I make this mistake the first time I tried to build graphene and the system cannot find the glib.pc or the graphene.pc file: at the end the problem was that I have the msys path before the gtk builded one and so the build system doesn't find the files and use the pkgconfig dir from msys.
The bad thing is that if I had installed glib or the gtk+ stack on msys (something I do to see how gtkmm and broadway works) the glib.pc files will be installed and our stack will found the msys one instead of giving an error.
I found that on windows the best thing to do with this stack is to drop every extra dirs on path: I use the open watcom suite and normally I have some include or libpath set, or I have an old wget or patch version on my path and, random, the build script gives me error.
I have done a simple batch that drop all the set that can cause problems and put the path to the minimum: the windows directory (C:\windows and c:\windows\system32) and the python one (c:\dev\py35-gtk3, a virtualenv installation from the 3.5.2 version) to avoid errors and be (almost) sure to have always the same result.
I used scons to build our stuff at work and the fact that nothing is imported, automatically, from the environment helps you to be esplicit on what you want (but it's not the panacea to all the bads that's can happen in a build systems, sometimes a 'SET CC=clang' before a make call can save your day).

To take a long story short: the pkg-config stuff seems to work correctly, we just must be careful on how we call it.

**Comment by TingPing** [comment]
It should be fairly easy to avoid issues like that. `meson` respects the `PKG_CONFIG` env var which can be an absolute path. I think that honestly should just always solve your issue but you could go futher and sanitize env vars like `PKG_CONFIG_PATH`.

**Pull request merged**
